### ISSUE TITLE
Callback url for github strategy

### ISSUE THREAD

**Issue by KonstantinSimeonov** [thoughtbot/yesod-auth-oauth2#102]
What callback will yesod accept for the github strategy? I tried different callback urls but none seemed to work.

**Comment by pbrisbin** [comment]
```
{APPROOT}/auth/page/{plugin}/callback
```

Here is what I use for my example/test application, run locally:

![](https://files.pbrisbin.com/screenshots/screenshot.6153.png)

**Comment by pbrisbin** [comment]
Note that this depends on you doing the common thing for you [main auth route](https://github.com/thoughtbot/yesod-auth-oauth2/blob/master/example/Main.hs#L57)
