### ISSUE TITLE
Build error on Windows 10

### ISSUE THREAD

**Issue by chromezh** [thoughtbot/yesod-auth-oauth2#120]
The problem is about `Yesod.Auth.OAuth2.GitHub` and `Yesod.Auth.OAuth2.Github`. On Windows 10 the two file names, `GitHub.hs` and `Github.hs`, are treated as the same. Therefore, when cloning, the content of one file overrides the other, and the error occurs:

```
<path to repository>\src\Yesod\Auth\OAuth2\GitHub.hs:1:8: error:
    File name does not match module name:
    Saw: ‘Yesod.Auth.OAuth2.Github’
    Expected: ‘Yesod.Auth.OAuth2.GitHub’
  |
1 | module Yesod.Auth.OAuth2.Github
  |        ^^^^^^^^^^^^^^^^^^^^^^^^
```

**Comment by pbrisbin** [comment]
Oh jeeze, that's rough. How do windows folks normally deal with this?

This is a just a temporary thing until we do a major version bump and can remove the wrongly-named module -- maybe we just do that sooner than later?

**Comment by pbrisbin** [comment]
I removed the deprecated module in 0.6.0.0, so only `GitHub` exists in the package as of that version. I believe that should resolve things?

**Comment by chromezh** [comment]
I do not know how to see 0.6.0.0 directly on GitHub, but I did the same modification on a local project, and the build now succeed.

Thanks!

**Comment by pbrisbin** [comment]
> I do not know how to see 0.6.0.0 directly on GitHub

Sorry about that. Hackage timed out so my release script didn't move onto to creating and pushing the tag. Should be fixed now: https://github.com/thoughtbot/yesod-auth-oauth2/tree/v0.6.0.0
