### ISSUE TITLE
Google+ Sign-in deprecation

### ISSUE THREAD

**Issue by ivanperez-keera** [thoughtbot/yesod-auth-oauth2#121]
I just got an email saying that a yesod web app that we have running is using Google+ sign in for authentication.

I've looked at this code and I believe this does not use Google+ but simply Google sign on, but I'm not an expert and I'd rather check ahead of time than wait to find out all users are locked out.

Is this going to be affected by the deprecation of Google+'s API [1]?

[1] https://developers.google.com/+/api-shutdown

**Comment by pbrisbin** [comment]
Thanks for bringing this up.

Google is notoriously vague with this stuff, so I have no guarantees about what will happen to my or your apps running this plugin when these dates come and go, unfortunately.

That said, it also seems to me that we are **not** using Google+ APIs here. It's very clear the URLs we're using in the plugin:

- `https://accounts.google.com/o/oauth2/auth`
- `https://www.googleapis.com/oauth2/v3/token`

And these are (modulo versions) the same endpoints documented in the [non-deprecated OAuth2 path for Google Sign-on](https://developers.google.com/identity/protocols/OAuth2InstalledApp), which are:

- `https://accounts.google.com/o/oauth2/v2/auth`
- `https://www.googleapis.com/oauth2/v4/token`

We then use this end-point to get the current user's info:

- `https://www.googleapis.com/oauth2/v3/userinfo`

And that should also be a valid API endpoint and un-related to Google+.

Is it possible to follow up through the email you received and see exactly what endpoints are being used by your app?

**Comment by jferris** [comment]
Is it possible you're requesting some scopes related to Google+?

**Comment by pbrisbin** [comment]
The default scopes are `openid` and `email`. AFAICT, these both still supported. @ivanperez-keera are you using the `Scoped` function with your own scopes?

**Comment by ivanperez-keera** [comment]
The email says we are sending requests to 'plus.people.get'.

The code for this yesod page has not changed much in years. The only use of Google's API is for authentication. Did this package ever use the old API? Maybe our yesod app is just using an old version.

**Comment by ivanperez-keera** [comment]
Thanks. Currently, it is (still) compiling using 'yesod-auth-1.4.5' and using 'Yesod.Auth.GoogleEmail2'.

**Comment by pbrisbin** [comment]
Oh yeah, that's not even this library. Migrating to us might be a good fix!
