### ISSUE TITLE
Migrating from Yesod.Auth.GoogleEmail2

### ISSUE THREAD

**Issue by pbrisbin** [thoughtbot/yesod-auth-oauth2#123]
## Context

Our `Google` plugin has always had overlap with the `GoogleEmail2` plugin of `yesod-auth`. There was even [previous discussion](https://github.com/thoughtbot/yesod-auth-oauth2/pull/32) to deprecate it for this. Now that the Google+ APIs are being deprecated (which that plugin relies on, but ours does not), it makes sense to re-open and resolve that discussion. What was always missing was a documented migration path for users of `GoogleEmail2`.

Therefore, this issue is a draft of said documentation. Once approved and committed in the appropriate location, `GoogleEmail2` can be deprecated and users can be pointed to this library and that documentation.

## Proposed Documentation

**Draft has moved to a post on my personal blog**: https://github.com/pbrisbin/pbrisbin.com/pull/13

Ping @snoyberg

**Comment by pbrisbin** [comment]
I'm going to get started fleshing this out as a blog post. Then we can point to it form wherever.

**Comment by snoyberg** [comment]
Sorry I didn't respond yet, I intended to look into this but haven't had a
chance. I'm in favor of this direction.

**Comment by pbrisbin** [comment]
Thanks @snoyberg I drafted a post as a PR on my blog source and replaced this Issue with a link to it. Hopefully this makes it easy for you to review, when you have time. I won't consider you blocking but will give you some time before I post it.

**Comment by snoyberg** [comment]
I've pushed a commit moving Haskellers over to this module: https://github.com/snoyberg/haskellers/commit/f77bba90d9684afb532639c68e64449523992535

**Comment by pbrisbin** [comment]
Blog post published: https://pbrisbin.com/posts/googleemail2_deprecation/
