### ISSUE TITLE
Add OAuth2.Twitter

### ISSUE THREAD

**Issue by pbrisbin** [thoughtbot/yesod-auth-oauth2#25]

**Comment by gabebw** [comment]
This exists: https://github.com/thoughtbot/yesod-auth-oauth2/blob/master/Yesod/Auth/OAuth2/Twitter.hs

However, I believe we should remove it:

* I couldn't get this working in my project
* [Yesod.Auth.OAuth](https://hackage.haskell.org/package/yesod-auth-oauth-1.4.0.2/docs/Yesod-Auth-OAuth.html) works with Twitter
* Twitter's [documentation](https://dev.twitter.com/oauth) claims they only support OAuth 1:

> There are two forms of authentication in the new model, both still leveraging OAuth 1.0A.
