### ISSUE TITLE
"login invalid" for Google

### ISSUE THREAD

**Issue by codygman** [thoughtbot/yesod-auth-oauth2#47]
I'm still debugging this and I believe I set everything up correctly, but I keep getting login invalid after confirming I want to allow my application to access my account.

**Comment by codygman** [comment]
Looks like my users are never actually inserted into the database.

**Comment by pbrisbin** [comment]
Thanks for the report. Are you able to post the relevant code where you use the plugin? Or better, a minimally reproducing repo? If not, I'll try to set something up this week where I can test the behavior of the plugin myself.

Please note that the plugin is not in charge of the database insert, so a lack of users in the DB doesn't necessarily indicate a problem in the plugin -- you could be mishandling the auth result, for example.

**Comment by codygman** [comment]
It looks like the problem was upstream:
https://github.com/yesodweb/yesod/issues/1133

**Comment by pbrisbin** [comment]
OK, thanks for letting me know.
