### ISSUE TITLE
Build with aeson 0.10 & http-types 0.9

### ISSUE THREAD

**Issue by DanBurton** [thoughtbot/yesod-auth-oauth2#48]
yesod-auth-oauth2 is currently being excluded from stackage since it isn't compatible with these dependencies.

See: https://github.com/fpco/stackage/issues/845 and https://github.com/fpco/stackage/issues/880

**Comment by pbrisbin** [comment]
Thanks for the report. I'll try to get this addressed this week.

**Comment by pbrisbin** [comment]
I've bumped the version bounds and ran `stack build --resolver nightly-2016-01-03`, but I see:

```
While constructing the BuildPlan the following exceptions were encountered:

--  While attempting to add dependency,
    Could not find package hoauth2 in known packages

--  Failure when adding dependencies:    
      hoauth2: needed (>=0.4.7 && <0.5), not present in build plan (latest applicable is 0.4.8)
    needed for package: yesod-auth-oauth2-0.1.5
```

If there's a workaround, let me know, but it seems we're blocked until hoauth2-0.4.8 (also mentioned in your linked issues) is addressed.

**Comment by DanBurton** [comment]
You're right; hoauth2 needs to make the same upgrades, since yesod-auth-oauth2 depends on it. I've opened an issue over there as well.

**Comment by DanBurton** [comment]
A new version of hoauth2 is available (0.5), and it is included in nightly-2016-01-08, since the author of hoauth2 has added himself to stackage. Try again?

**Comment by pbrisbin** [comment]
Released with bounds change as 0.1.6.

**Comment by DanBurton** [comment]
Nice, thanks! I've opened a PR to restore yesod-auth-oauth2 to stackage:
https://github.com/fpco/stackage/pull/1110

**Comment by pbrisbin** [comment]
Awesome, thanks for handling the stackage end of this -- anything I should look at about the build errors over there?

**Comment by DanBurton** [comment]
The travis build error on that PR is due to reasons other than the PR itself, so, nothing to worry about.
