### ISSUE TITLE
get the 'location' for github authentication

### ISSUE THREAD

**Issue by silky** [thoughtbot/yesod-auth-oauth2#49]
this should come back as part of the authentication process, if it's available. (potentially only if it's in the list of "scopes" that has been provided.)

**Comment by pbrisbin** [comment]
I'm unfamiliar with this field; does it come back in the `/user` API response, or would we need another call? If you could link to some docs on it that'd be great.

I'm generally fine throwing whatever folks find useful into `credsExtras`, as long as it's not to complicate to get or build the value.

**Comment by silky** [comment]
it appears to come back in the `/user` response already: https://developer.github.com/v3/users/#get-the-authenticated-user as `location`
