### ISSUE TITLE
consider checking public github email address then falling back to /user/email

### ISSUE THREAD

**Issue by silky** [thoughtbot/yesod-auth-oauth2#54]
github returns the "public" address via `/users/:username`, and if this is `null` we could fall back to the current method of returning the first primary or just first email.

some users (in particular, me) have a different public email address set then the ones that come back from `/user/emails`.

see - https://developer.github.com/v3/users/

**Comment by jferris** [comment]
Is this addressed by #52?

**Comment by silky** [comment]
no, it's not.

the observation here is that the github api is a little bit confusing.

a single-user query, as seen in the provided link, *does* provide an email address in the `"email"` field, which can be queried *without authentication*.

alternatively, and this is what this code currently does, you can query https://developer.github.com/v3/users/emails/ and obtain a list, which we can then determine an email from (by looking at which one is primary).

so i'm suggesting here that we could firstly try this "public" email address, see if it is set, and use it; then secondarily go for the `primary` email address in the authenticated request for emails.

either way, it's kind of a quirk that we need to make a decision like this, because other oauth plugins might try to get the email different ways. if we do make a change here, we should probably follow some other oauth plugins approach, so get some semblance of consistency.

**Comment by jferris** [comment]
I looked through a few GitHub client libraries:

* The [omniauth-github plugin for Ruby](https://github.com/intridea/omniauth-github/blob/master/lib/omniauth/strategies/github.rb) uses the primary email address. It also filters out unverified emails, which we currently don't do.
* It looks like the [Jenkins GitHub plugin](https://github.com/jenkinsci/github-oauth-plugin/blob/master/src/main/java/org/jenkinsci/plugins/GithubSecurityRealm.java) uses the primary email address.
* The [Go GitHub client](https://github.com/google/go-github/blob/master/github/users_emails.go) doesn't seem to provide any kind of function for getting a user's email. It provides direct mappings to the GitHub API, so developers will make the choice on their own.

There are more listed here: https://developer.github.com/libraries/

It takes a little digging to figure out which ones are direct mappings of the API and which are integrated into a login system like Yesod's.

Maybe it makes sense to keep returning the primary email, but also provide a "public_email" extras field when it's populated on the user's profile?

**Comment by silky** [comment]
i quite like that; simple, and leaves the option to the end user.
