### ISSUE TITLE
New release

### ISSUE THREAD

**Issue by zenhack** [thoughtbot/yesod-auth-oauth2#88]
0.2.4 won't build against base 4.10, because it specifies an upper bound of <0.12 on vector, which transitively specifies a version bound of <4.10 on base. I see the version has already been bumped on master; it would be nice to have that pushed to hackage. (Also, the URI stuff looks nice).

**Comment by pbrisbin** [comment]
Released as v0.3.0. Thanks for the reminder!

**Comment by zenhack** [comment]
You're welcome!
