### ISSUE TITLE
License uncertainty

### ISSUE THREAD

**Issue by pbrisbin** [thoughtbot/yesod-auth-oauth2#96]
The `LICENSE` file is a [BSD 2-clause](https://opensource.org/licenses/BSD-2-Clause) license naming Michael Snoyman through 2008. None of that is accurate :). The package file says `BSD3`, has an author and a maintainer, neither of which are Michael, and it's now 2018.

I want to resolve this. I would _like_ to just bring this in line with all my packages and switch it over the MIT, my name, current year. But I'm not sure if there are any implications to doing this.

I'm not worried in a legal sense; I'm confident that a license change like this just means the code prior to the commit is licensed as it was and the code after the commit is licensed as it is -- I just wouldn't want to cause any annoyance for anyone using this library in a corporate setting.

Considering the current situation is basically too vague to be meaningful (IMO), I'd think my proposed change would be a clear improvement from any perspective. So if no one objects over the next week or so, I'll go ahead with it.

Ping @snoyberg -- you probably don't know your name's on this or how it got there, but I just want to confirm you have no issues with me replacing the `LICENSE` here.

**Comment by jferris** [comment]
I have no objection to changing the license as you describe.
